driftinfo:
    email_from: ''
    password: ''
    send_to_email: ''

driftinfo_for_sms:
    sid = ''
    token = ''
    nummer = ''
    to_nummer = '' 

driftinfo_for_twitter:
   key = ''
   secret = ''
   token = ''
   token_secret = ''


