app:
    secret_key: 'kano0049'
driftinfo:
    email_from: ''
    password: ''
    send_to_email: ''

driftinfo_for_sms:
    sid: ''
    token: ''
    nummer: ''
    to_nummer: '' 

driftinfo_for_twitter:
    key: ''
    secret: ''
    token: ''
    token_secret: ''

driftinfo_for_database:
    path_to_database: '/local/driftinfo/db/driftinfo.db'

