# Flask app config
domain: ''
app:
    secret_key: ''
# Database config
database:
    path: '/local/driftinfo/db/driftinfo.db'
# Enumeration of plugins
plugins:
    - twitterapi:
    - generic_email:
        - mail
        - wordpress
        - sms
# Specific configuration for plugins
email:
    email_from: ''
    password: ''
    send_to_email_mail: ''
    send_to_email_sms: ''
    send_to_email_wordpress: ''

twitter:
    key: ''
    secret: ''
    token: ''
    token_secret: ''
