app:
    secret_key: ''
email:
    email_from: ''
    password: ''
    send_to_email_mail: ''
    send_to_email_sms: ''
    send_to_email_wordpress: ''

twitter:
    key: ''
    secret: ''
    token: ''
    token_secret: ''

database:
    path: '/local/driftinfo/db/driftinfo.db'

